### ISSUE TITLE
No MPM Loaded on Amazon

### ISSUE THREAD

**Issue by rryke** [svanzoest-cookbooks/apache2#329] opened 2015-03-16 16:55 UTC
I'm getting:Starting httpd: AH00534: httpd: Configuration error: No MPM loaded. On Amazon Linux. I've tried to change to worker and the default prefork in the attributes. Also tried to call the module mpm_prefork and mpm_worker as the named modules. I was also having issues with the cookbook installing 2.2, I changed the package name to httpd24 and that is working successfully now. 

Any ideas?

**Comment by svanzoest** [comment] 2015-03-18 04:33
We currently do not test or actively support Amazon Linux, but hope to add support for it in the future.
So, unfortunately I do not have any ideas on why it is not seeing an mpm module. Some platforms it is compiled in and can not be changed, you can try `httpd -V` to see.

**Comment by drpebcak** [comment] 2015-03-29 07:18
@rryke any movement on this? I'd like to see some debug information so we can figure out what went wrong.

**Comment by rryke** [comment] 2015-03-29 16:59
@drpebcak after @svanzoest 's comment, I moved over to the httpd cookbook. https://github.com/chef-cookbooks/httpd

It's not as full featured as this one, but it got the job done. If you'd like I can go back and get the logs.

**Comment by drpebcak** [comment] 2015-03-30 04:30
@rryke if you could, that would be great. I've only used Apache 2.4 on Amazon Linux, so I've never seen this. It sounds like the problem is only with 2.2?

**Comment by rryke** [comment] 2015-03-30 14:36
Did you use the Apache2 Cookbook for Amazon Linux?

Ryan Ryke
Cloud Life Consulting
424.286.4861
itsacloudlife.com

**Comment by drpebcak** [comment] 2015-03-30 14:42
@rryke yes. I've been making improvements so that there is Amazon Linux support.

**Comment by drpebcak** [comment] 2015-03-30 23:06
I'm going to close this for now, but I'd still love to see those logs @rryke.

**Closed by drpebcak** 2015-03-30 23:06 UTC
Labels: enhancement
